const basePath = 'domino/images'

export const images = {
  tiles: {
    seta: `${basePath}/distractors/seta.webp`,
    dado: `${basePath}/distractors/dado.webp`,
    lapa: `${basePath}/distractors/lapa.webp`,
    loto: `${basePath}/distractors/loto.webp`,
    luta: `${basePath}/distractors/luta.webp`,
    lata: `${basePath}/distractors/lata.webp`,
    lua: `${basePath}/distractors/lua.webp`,
    paio: `${basePath}/distractors/paio.webp`,
    leite: `${basePath}/distractors/leite.webp`,
    lula: `${basePath}/distractors/lula.webp`,
    pala: `${basePath}/distractors/pala.webp`,
    doido: `${basePath}/distractors/doido.webp`,
    lota: `${basePath}/distractors/lota.webp`,
    lupa: `${basePath}/distractors/lupa.webp`,
    papa: `${basePath}/distractors/papa.webp`,
    papo: `${basePath}/distractors/papo.webp`,
    pata: `${basePath}/distractors/pata.webp`,
    pato: `${basePath}/distractors/pato.webp`,
    pelo: `${basePath}/distractors/pelo.webp`,
    pia: `${basePath}/distractors/pia.webp`,
    pio: `${basePath}/distractors/pio.webp`,
    pipa: `${basePath}/distractors/pipa.webp`,
    pote: `${basePath}/distractors/pote.webp`,
    pula: `${basePath}/distractors/pula.webp`,
    tala: `${basePath}/distractors/tala.webp`,
    poupa: `${basePath}/distractors/poupa.webp`,
    toto: `${basePath}/distractors/toto.webp`,
    pau: `${basePath}/distractors/pau.webp`,
    pai: `${basePath}/distractors/pai.webp`,
    tatu: `${basePath}/distractors/tatu.webp`,
    teia: `${basePath}/distractors/teia.webp`,
    tela: `${basePath}/distractors/tela.webp`,
    tia: `${basePath}/distractors/tia.webp`,
    pe: `${basePath}/distractors/pe.webp`,
    pota: `${basePath}/distractors/pota.webp`,
    pa: `${basePath}/distractors/pa.webp`,
    bandeira: `${basePath}/distractors/bandeira.webp`,
  },
  ui: {
    background: `${basePath}/ui/background.webp`,
  },
}
