const basePath = 'domino/images'

export const images = {
  tiles: {
    seta: `${basePath}/seta.webp`,
    dado: `${basePath}/dado.webp`,
    lapa: `${basePath}/lapa.webp`,
    loto: `${basePath}/loto.webp`,
    luta: `${basePath}/luta.webp`,
    lata: `${basePath}/lata.webp`,
    lua: `${basePath}/lua.webp`,
    paio: `${basePath}/paio.webp`,
    leite: `${basePath}/leite.webp`,
    lula: `${basePath}/lula.webp`,
    pala: `${basePath}/pala.webp`,
    doido: `${basePath}/doido.webp`,
    lota: `${basePath}/lota.webp`,
    lupa: `${basePath}/lupa.webp`,
    papa: `${basePath}/papa.webp`,
    papo: `${basePath}/papo.webp`,
    pata: `${basePath}/pata.webp`,
    pato: `${basePath}/pato.webp`,
    pelo: `${basePath}/pelo.webp`,
    pia: `${basePath}/pia.webp`,
    pio: `${basePath}/pio.webp`,
    pipa: `${basePath}/pipa.webp`,
    pote: `${basePath}/pote.webp`,
    pula: `${basePath}/pula.webp`,
    tala: `${basePath}/tala.webp`,
    pai: `${basePath}/pai.webp`,
    tatu: `${basePath}/tatu.webp`,
    teia: `${basePath}/teia.webp`,
    tela: `${basePath}/tela.webp`,
    tia: `${basePath}/tia.webp`,
    poupa: `${basePath}/poupa.webp`,
    toto: `${basePath}/toto.webp`,
    pau: `${basePath}/pau.webp`,
    pe: `${basePath}/pe.webp`,
    pota: `${basePath}/pota.webp`,
    pa: `${basePath}/pa.webp`,
    bandeira: `${basePath}/bandeira.webp`,
  },
  ui: {
    background: `${basePath}/ui/background.webp`,
  },
}
