import { images } from './images'

const tiles: Tile[] = [
  {
    id: 1,
    src: images.tiles.seta,
    value: 'dado',
    mirrorImage: false,
    backgroundImagePosition: 'center',
  },
  {
    id: 2,
    src: images.tiles.dado,
    value: 'lapa',
    mirrorImage: false,
    backgroundImagePosition: 'center',
  },
  {
    id: 3,
    src: images.tiles.lapa,
    value: 'loto',
    mirrorImage: false,
    backgroundImagePosition: 'center',
  },
  {
    id: 4,
    src: images.tiles.loto,
    value: 'luta',
    mirrorImage: false,
    backgroundImagePosition: 'center',
  },
  {
    id: 5,
    src: images.tiles.luta,
    value: 'lata',
    mirrorImage: false,
    backgroundImagePosition: 'center',
  },
  {
    id: 6,
    src: images.tiles.lata,
    value: 'lua',
    mirrorImage: true,
    backgroundImagePosition: 'right bottom',
  },
  {
    id: 7,
    src: images.tiles.lua,
    value: 'paio',
    mirrorImage: false,
    backgroundImagePosition: 'center',
  },
  {
    id: 8,
    src: images.tiles.paio,
    value: 'leite',
    mirrorImage: false,
  },
  {
    id: 9,
    src: images.tiles.leite,
    value: 'lula',
    mirrorImage: true,
    backgroundImagePosition: 'right bottom',
  },
  // Level 2
  {
    id: 10,
    src: images.tiles.lula,
    value: 'pala',
    mirrorImage: false,
    backgroundImagePosition: 'center',
  },
  {
    id: 11,
    src: images.tiles.pala,
    value: 'doido',
    mirrorImage: true,
    backgroundImagePosition: 'right bottom',
  },
  {
    id: 12,
    src: images.tiles.doido,
    value: 'lota',
    mirrorImage: false,
  },
  {
    id: 13,
    src: images.tiles.lota,
    value: 'lupa',
    mirrorImage: true,
    backgroundImagePosition: 'right bottom',
  },
  {
    id: 14,
    src: images.tiles.lupa,
    value: 'papa',
    mirrorImage: true,
    backgroundImagePosition: 'right bottom',
  },
  {
    id: 15,
    src: images.tiles.papa,
    value: 'papo',
    mirrorImage: false,
  },
  {
    id: 16,
    src: images.tiles.papo,
    value: 'pata',
    mirrorImage: false,
  },
  {
    id: 17,
    src: images.tiles.pata,
    value: 'pato',
    mirrorImage: false,
    backgroundImagePosition: 'left bottom',
  },
  {
    id: 18,
    src: images.tiles.pato,
    value: 'pelo',
    mirrorImage: true,
    backgroundImagePosition: 'right bottom',
  },
  // Level 3
  {
    id: 19,
    src: images.tiles.pelo,
    value: 'pia',
    mirrorImage: false,
  },
  {
    id: 20,
    src: images.tiles.pia,
    value: 'pio',
    mirrorImage: true,
    backgroundImagePosition: 'right bottom',
  },
  {
    id: 21,
    src: images.tiles.pio,
    value: 'pipa',
    mirrorImage: true,
    backgroundImagePosition: 'right bottom',
  },
  {
    id: 22,
    src: images.tiles.pipa,
    value: 'pote',
    mirrorImage: false,
  },
  {
    id: 23,
    src: images.tiles.pote,
    value: 'pula',
    mirrorImage: false,
  },
  {
    id: 24,
    src: images.tiles.pula,
    value: 'tala',
    mirrorImage: false,
  },
  {
    id: 25,
    src: images.tiles.tala,
    value: 'pai',
    mirrorImage: false,
  },
  {
    id: 26,
    src: images.tiles.pai,
    value: 'tatu',
    mirrorImage: true,
    backgroundImagePosition: 'right bottom',
  },
  {
    id: 27,
    src: images.tiles.tatu,
    value: 'teia',
    mirrorImage: true,
    backgroundImagePosition: 'right bottom',
  },
  // Level 4
  {
    id: 28,
    src: images.tiles.teia,
    value: 'tela',
    mirrorImage: true,
    backgroundImagePosition: 'right bottom',
  },
  {
    id: 29,
    src: images.tiles.tela,
    value: 'tia',
    mirrorImage: false,
  },
  {
    id: 30,
    src: images.tiles.tia,
    value: 'poupa',
    mirrorImage: false,
  },
  {
    id: 31,
    src: images.tiles.poupa,
    value: 'totó',
    mirrorImage: true,
    backgroundImagePosition: 'right bottom',
  },
  {
    id: 32,
    src: images.tiles.toto,
    value: 'pau',
    mirrorImage: false,
  },
  {
    id: 33,
    src: images.tiles.pau,
    value: 'pé',
    mirrorImage: false,
  },
  {
    id: 34,
    src: images.tiles.pe,
    value: 'pota',
    mirrorImage: false,
  },
  {
    id: 35,
    src: images.tiles.pota,
    value: 'pá',
    mirrorImage: false,
  },
  {
    id: 36,
    src: images.tiles.pa,
    rightImage: images.tiles.bandeira,
    mirrorImage: false,
  },
]

export default tiles
